version: '3.9'
services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: comments
      HOST_AUTH_METHOD: trust
  adminer:
    image: adminer
    restart: always
